//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
// 
#pragma warning disable 1591

namespace Com.CritSend.Connector.com.messaging_master.mail {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSDL 0.1 for MxMasterBinding", Namespace="http://mxmaster.net/campaign/0.1")]
    public partial class WSDL01forMxMaster : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendCampaignOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback createTagOperationCompleted;
        
        private System.Threading.SendOrPostCallback resetTagOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteTagOperationCompleted;
        
        private System.Threading.SendOrPostCallback listAllTagsOperationCompleted;
        
        private System.Threading.SendOrPostCallback isTagOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTagOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTagPaginatedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSDL01forMxMaster() {
            this.Url = global::Com.CritSend.Connector.Properties.Settings.Default.Com_CritSend_Connector_com_messaging_master_mail_WSDL_0_1_for_MxMaster;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendCampaignCompletedEventHandler sendCampaignCompleted;
        
        /// <remarks/>
        public event sendEmailCompletedEventHandler sendEmailCompleted;
        
        /// <remarks/>
        public event createTagCompletedEventHandler createTagCompleted;
        
        /// <remarks/>
        public event resetTagCompletedEventHandler resetTagCompleted;
        
        /// <remarks/>
        public event deleteTagCompletedEventHandler deleteTagCompleted;
        
        /// <remarks/>
        public event listAllTagsCompletedEventHandler listAllTagsCompleted;
        
        /// <remarks/>
        public event isTagCompletedEventHandler isTagCompleted;
        
        /// <remarks/>
        public event getTagCompletedEventHandler getTagCompleted;
        
        /// <remarks/>
        public event getTagPaginatedCompletedEventHandler getTagPaginatedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://mxmaster.net/campaign/0.1#doCampaign", RequestNamespace="http://mxmaster.net/campaign/0.1", ResponseNamespace="http://mxmaster.net/campaign/0.1", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool sendCampaign(Authentication authentication, [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] Email[] subscribers, CampaignParameters parameters, Content content) {
            object[] results = this.Invoke("sendCampaign", new object[] {
                        authentication,
                        subscribers,
                        parameters,
                        content});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void sendCampaignAsync(Authentication authentication, Email[] subscribers, CampaignParameters parameters, Content content) {
            this.sendCampaignAsync(authentication, subscribers, parameters, content, null);
        }
        
        /// <remarks/>
        public void sendCampaignAsync(Authentication authentication, Email[] subscribers, CampaignParameters parameters, Content content, object userState) {
            if ((this.sendCampaignOperationCompleted == null)) {
                this.sendCampaignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendCampaignOperationCompleted);
            }
            this.InvokeAsync("sendCampaign", new object[] {
                        authentication,
                        subscribers,
                        parameters,
                        content}, this.sendCampaignOperationCompleted, userState);
        }
        
        private void OnsendCampaignOperationCompleted(object arg) {
            if ((this.sendCampaignCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendCampaignCompleted(this, new sendCampaignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://mxmaster.net/campaign/0.1#doCampaign", RequestNamespace="http://mxmaster.net/campaign/0.1", ResponseNamespace="http://mxmaster.net/campaign/0.1", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool sendEmail(Authentication authentication, [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] Email[] subscribers, CampaignParameters parameters, Content content) {
            object[] results = this.Invoke("sendEmail", new object[] {
                        authentication,
                        subscribers,
                        parameters,
                        content});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void sendEmailAsync(Authentication authentication, Email[] subscribers, CampaignParameters parameters, Content content) {
            this.sendEmailAsync(authentication, subscribers, parameters, content, null);
        }
        
        /// <remarks/>
        public void sendEmailAsync(Authentication authentication, Email[] subscribers, CampaignParameters parameters, Content content, object userState) {
            if ((this.sendEmailOperationCompleted == null)) {
                this.sendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendEmailOperationCompleted);
            }
            this.InvokeAsync("sendEmail", new object[] {
                        authentication,
                        subscribers,
                        parameters,
                        content}, this.sendEmailOperationCompleted, userState);
        }
        
        private void OnsendEmailOperationCompleted(object arg) {
            if ((this.sendEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendEmailCompleted(this, new sendEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://mxmaster.net/campaign/0.1#doCampaign", RequestNamespace="http://mxmaster.net/campaign/0.1", ResponseNamespace="http://mxmaster.net/campaign/0.1", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool createTag(Authentication authentication, string tag) {
            object[] results = this.Invoke("createTag", new object[] {
                        authentication,
                        tag});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void createTagAsync(Authentication authentication, string tag) {
            this.createTagAsync(authentication, tag, null);
        }
        
        /// <remarks/>
        public void createTagAsync(Authentication authentication, string tag, object userState) {
            if ((this.createTagOperationCompleted == null)) {
                this.createTagOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateTagOperationCompleted);
            }
            this.InvokeAsync("createTag", new object[] {
                        authentication,
                        tag}, this.createTagOperationCompleted, userState);
        }
        
        private void OncreateTagOperationCompleted(object arg) {
            if ((this.createTagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createTagCompleted(this, new createTagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://mxmaster.net/campaign/0.1#doCampaign", RequestNamespace="http://mxmaster.net/campaign/0.1", ResponseNamespace="http://mxmaster.net/campaign/0.1", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool resetTag(Authentication authentication, string tag) {
            object[] results = this.Invoke("resetTag", new object[] {
                        authentication,
                        tag});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void resetTagAsync(Authentication authentication, string tag) {
            this.resetTagAsync(authentication, tag, null);
        }
        
        /// <remarks/>
        public void resetTagAsync(Authentication authentication, string tag, object userState) {
            if ((this.resetTagOperationCompleted == null)) {
                this.resetTagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresetTagOperationCompleted);
            }
            this.InvokeAsync("resetTag", new object[] {
                        authentication,
                        tag}, this.resetTagOperationCompleted, userState);
        }
        
        private void OnresetTagOperationCompleted(object arg) {
            if ((this.resetTagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.resetTagCompleted(this, new resetTagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://mxmaster.net/campaign/0.1#doCampaign", RequestNamespace="http://mxmaster.net/campaign/0.1", ResponseNamespace="http://mxmaster.net/campaign/0.1", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool deleteTag(Authentication authentication, string tag) {
            object[] results = this.Invoke("deleteTag", new object[] {
                        authentication,
                        tag});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteTagAsync(Authentication authentication, string tag) {
            this.deleteTagAsync(authentication, tag, null);
        }
        
        /// <remarks/>
        public void deleteTagAsync(Authentication authentication, string tag, object userState) {
            if ((this.deleteTagOperationCompleted == null)) {
                this.deleteTagOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteTagOperationCompleted);
            }
            this.InvokeAsync("deleteTag", new object[] {
                        authentication,
                        tag}, this.deleteTagOperationCompleted, userState);
        }
        
        private void OndeleteTagOperationCompleted(object arg) {
            if ((this.deleteTagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteTagCompleted(this, new deleteTagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://mxmaster.net/campaign/0.1#doCampaign", RequestNamespace="http://mxmaster.net/campaign/0.1", ResponseNamespace="http://mxmaster.net/campaign/0.1", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Tag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] listAllTags(Authentication authentication) {
            object[] results = this.Invoke("listAllTags", new object[] {
                        authentication});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void listAllTagsAsync(Authentication authentication) {
            this.listAllTagsAsync(authentication, null);
        }
        
        /// <remarks/>
        public void listAllTagsAsync(Authentication authentication, object userState) {
            if ((this.listAllTagsOperationCompleted == null)) {
                this.listAllTagsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistAllTagsOperationCompleted);
            }
            this.InvokeAsync("listAllTags", new object[] {
                        authentication}, this.listAllTagsOperationCompleted, userState);
        }
        
        private void OnlistAllTagsOperationCompleted(object arg) {
            if ((this.listAllTagsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listAllTagsCompleted(this, new listAllTagsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://mxmaster.net/campaign/0.1#doCampaign", RequestNamespace="http://mxmaster.net/campaign/0.1", ResponseNamespace="http://mxmaster.net/campaign/0.1", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool isTag(Authentication authentication, string tag) {
            object[] results = this.Invoke("isTag", new object[] {
                        authentication,
                        tag});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void isTagAsync(Authentication authentication, string tag) {
            this.isTagAsync(authentication, tag, null);
        }
        
        /// <remarks/>
        public void isTagAsync(Authentication authentication, string tag, object userState) {
            if ((this.isTagOperationCompleted == null)) {
                this.isTagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisTagOperationCompleted);
            }
            this.InvokeAsync("isTag", new object[] {
                        authentication,
                        tag}, this.isTagOperationCompleted, userState);
        }
        
        private void OnisTagOperationCompleted(object arg) {
            if ((this.isTagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isTagCompleted(this, new isTagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://mxmaster.net/campaign/0.1#doCampaign", RequestNamespace="http://mxmaster.net/campaign/0.1", ResponseNamespace="http://mxmaster.net/campaign/0.1", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getTag(Authentication authentication, string tag) {
            object[] results = this.Invoke("getTag", new object[] {
                        authentication,
                        tag});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTagAsync(Authentication authentication, string tag) {
            this.getTagAsync(authentication, tag, null);
        }
        
        /// <remarks/>
        public void getTagAsync(Authentication authentication, string tag, object userState) {
            if ((this.getTagOperationCompleted == null)) {
                this.getTagOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTagOperationCompleted);
            }
            this.InvokeAsync("getTag", new object[] {
                        authentication,
                        tag}, this.getTagOperationCompleted, userState);
        }
        
        private void OngetTagOperationCompleted(object arg) {
            if ((this.getTagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTagCompleted(this, new getTagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://mxmaster.net/campaign/0.1#doCampaign", RequestNamespace="http://mxmaster.net/campaign/0.1", ResponseNamespace="http://mxmaster.net/campaign/0.1", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string getTagPaginated(Authentication authentication, string tag, int start, int offset) {
            object[] results = this.Invoke("getTagPaginated", new object[] {
                        authentication,
                        tag,
                        start,
                        offset});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTagPaginatedAsync(Authentication authentication, string tag, int start, int offset) {
            this.getTagPaginatedAsync(authentication, tag, start, offset, null);
        }
        
        /// <remarks/>
        public void getTagPaginatedAsync(Authentication authentication, string tag, int start, int offset, object userState) {
            if ((this.getTagPaginatedOperationCompleted == null)) {
                this.getTagPaginatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTagPaginatedOperationCompleted);
            }
            this.InvokeAsync("getTagPaginated", new object[] {
                        authentication,
                        tag,
                        start,
                        offset}, this.getTagPaginatedOperationCompleted, userState);
        }
        
        private void OngetTagPaginatedOperationCompleted(object arg) {
            if ((this.getTagPaginatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTagPaginatedCompleted(this, new getTagPaginatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mxmaster.net/campaign/0.1")]
    public partial class Authentication {
        
        private string userField;
        
        private System.DateTime timestampField;
        
        private string signatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mxmaster.net/campaign/0.1")]
    public partial class Content {
        
        private string subjectField;
        
        private string htmlField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string html {
            get {
                return this.htmlField;
            }
            set {
                this.htmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mxmaster.net/campaign/0.1")]
    public partial class CampaignParameters {
        
        private string[] tagField;
        
        private string mailfromField;
        
        private string mailfrom_friendlyField;
        
        private string replytoField;
        
        private bool replyto_filteredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mailfrom {
            get {
                return this.mailfromField;
            }
            set {
                this.mailfromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mailfrom_friendly {
            get {
                return this.mailfrom_friendlyField;
            }
            set {
                this.mailfrom_friendlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string replyto {
            get {
                return this.replytoField;
            }
            set {
                this.replytoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool replyto_filtered {
            get {
                return this.replyto_filteredField;
            }
            set {
                this.replyto_filteredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mxmaster.net/campaign/0.1")]
    public partial class Email {
        
        private string emailField;
        
        private string field1Field;
        
        private string field2Field;
        
        private string field3Field;
        
        private string field4Field;
        
        private string field5Field;
        
        private string field6Field;
        
        private string field7Field;
        
        private string field8Field;
        
        private string field9Field;
        
        private string field10Field;
        
        private string field11Field;
        
        private string field12Field;
        
        private string field13Field;
        
        private string field14Field;
        
        private string field15Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field1 {
            get {
                return this.field1Field;
            }
            set {
                this.field1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field2 {
            get {
                return this.field2Field;
            }
            set {
                this.field2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field3 {
            get {
                return this.field3Field;
            }
            set {
                this.field3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field4 {
            get {
                return this.field4Field;
            }
            set {
                this.field4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field5 {
            get {
                return this.field5Field;
            }
            set {
                this.field5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field6 {
            get {
                return this.field6Field;
            }
            set {
                this.field6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field7 {
            get {
                return this.field7Field;
            }
            set {
                this.field7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field8 {
            get {
                return this.field8Field;
            }
            set {
                this.field8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field9 {
            get {
                return this.field9Field;
            }
            set {
                this.field9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field10 {
            get {
                return this.field10Field;
            }
            set {
                this.field10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field11 {
            get {
                return this.field11Field;
            }
            set {
                this.field11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field12 {
            get {
                return this.field12Field;
            }
            set {
                this.field12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field13 {
            get {
                return this.field13Field;
            }
            set {
                this.field13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field14 {
            get {
                return this.field14Field;
            }
            set {
                this.field14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string field15 {
            get {
                return this.field15Field;
            }
            set {
                this.field15Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void sendCampaignCompletedEventHandler(object sender, sendCampaignCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendCampaignCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendCampaignCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void sendEmailCompletedEventHandler(object sender, sendEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void createTagCompletedEventHandler(object sender, createTagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createTagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createTagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void resetTagCompletedEventHandler(object sender, resetTagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resetTagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal resetTagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void deleteTagCompletedEventHandler(object sender, deleteTagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteTagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteTagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void listAllTagsCompletedEventHandler(object sender, listAllTagsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listAllTagsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listAllTagsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void isTagCompletedEventHandler(object sender, isTagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isTagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isTagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void getTagCompletedEventHandler(object sender, getTagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void getTagPaginatedCompletedEventHandler(object sender, getTagPaginatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTagPaginatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTagPaginatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591